## **PANDAS PROJECT 1 : Data Cleaning on Amazon Fires Dataset**

##### Import Neccessary Libraries

In [409]:
import pandas as pd
import numpy as np

##### Read the Amazon Fires CSV File

In [410]:
df = pd.read_csv("amazon_fires.csv",encoding='ISO-8859-4')

In [411]:
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

#### **Exploratory Data Analysis**

##### Get the Unique values of Mes column to understand the data

In [412]:
df['mes'].unique()

array(['Janeiro', 'Fevereiro', 'Marįo', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

##### Since it is Spanish Language , Mes means Months we need to change the columns name mes to month

In [413]:
new_columns = {'ano':'Year','mes':'Month','estado':'State','numero':'Number','encontro':'Meeting_Date'}

In [414]:
new_columns

{'ano': 'Year',
 'mes': 'Month',
 'estado': 'State',
 'numero': 'Number',
 'encontro': 'Meeting_Date'}

##### changing the column names

In [415]:
df.rename(columns=new_columns,inplace=True)

In [417]:
df.sample(5)

      Year     Month             State   Number Meeting_Date
1498  2001     Abril  Distrito Federal  0 Fires     1/1/2001
302   2000     Abril           alagoas       20     1/1/2000
80    1998      Maio              Acre  0 Fires     1/1/1998
328   2006      Maio           alagoas        0     1/1/2006
5905  2006  Setembro         Sao Paulo      694     1/1/2006

##### Check that any column contains any null values or not. If yes replace or fill by other value.

In [418]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          6454 non-null   int64
 1   Month         6454 non-null   object
 2   State         6454 non-null   object
 3   Number        6322 non-null   object
 4   Meeting_Date  6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

##### To check the total Number of duplicates we need to use duplicated.

In [419]:
df.duplicated().sum()

np.int64(30)

##### To drop the duplicates we have to use drop_duplicated.

In [420]:
df.drop_duplicates(inplace=True)

In [421]:
df.duplicated().sum()

np.int64(0)

##### again check whether we have duplicate and null values or not.6454 entries to 6424 entries totaly 30 duplicate records are deleted.

In [422]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          6424 non-null   int64
 1   Month         6424 non-null   object
 2   State         6424 non-null   object
 3   Number        6292 non-null   object
 4   Meeting_Date  6424 non-null   object
dtypes: int64(1), object(4)
memory usage: 301.1+ KB

In [423]:
df.head(3)

   Year    Month State   Number Meeting_Date
0  1998  Janeiro  Acre  0 Fires     1/1/1998
1  1999  Janeiro  Acre  0 Fires     1/1/1999
2  2000  Janeiro  Acre  0 Fires     1/1/2000

##### Get the unique values of Month table to rename the month present in spanish to convert it into english.

In [424]:
df['Month'].unique()

array(['Janeiro', 'Fevereiro', 'Marįo', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

##### We have to rename all the spanish months to English months name.

In [425]:
new_month = {'Janeiro':'Jan', 'Fevereiro':'Feb', 'Marįo':'mar', 'Abril':'apr', 'Maio':'may', 'Junho':'June', 'Julho':'July',
       'Agosto':'aug', 'Setembro':'September', 'Outubro':'oct', 'Novembro':'Nov', 'Dezembro':'Dec'}

In [426]:
new_month

{'Janeiro': 'Jan',
 'Fevereiro': 'Feb',
 'Marįo': 'mar',
 'Abril': 'apr',
 'Maio': 'may',
 'Junho': 'June',
 'Julho': 'July',
 'Agosto': 'aug',
 'Setembro': 'September',
 'Outubro': 'oct',
 'Novembro': 'Nov',
 'Dezembro': 'Dec'}

##### See it is not changed the Months name to change it we need use map() method to map new_month to month column

In [427]:
df['Month']

0        Janeiro
1        Janeiro
2        Janeiro
3        Janeiro
4        Janeiro
          ...
6449    Dezembro
6450    Dezembro
6451    Dezembro
6452    Dezembro
6453    Dezembro
Name: Month, Length: 6424, dtype: object

In [428]:
df['Month'] = df['Month'].map(new_month)

In [429]:
df['Month']

0       Jan
1       Jan
2       Jan
3       Jan
4       Jan
       ...
6449    Dec
6450    Dec
6451    Dec
6452    Dec
6453    Dec
Name: Month, Length: 6424, dtype: object

In [430]:
df.sample(5)

      Year Month        State Number Meeting_Date
4125  1999   apr         Piau     10     1/1/1999
2620  2007   Dec  Mato Grosso     81     1/1/2007
4929  2006   aug          Rio    642     1/1/2006
2657  2005   Feb  Mato Grosso    221     1/1/2005
5277  2016   Jan      Roraima  1.754     1/1/2016

##### Again Here data is not present in same case alphabets and Not is proper format to make it proper format we have to replace all months with first letter should be upper case followed by lowercase and Should be same format . Like we should convert jan -> January or January-> Jan

In [431]:
df['Month'].unique()

array(['Jan', 'Feb', 'mar', 'apr', 'may', 'June', 'July', 'aug',
       'September', 'oct', 'Nov', 'Dec'], dtype=object)

In [432]:
df['Month'].replace('September','sept',inplace=True)

In [433]:
df['Month'].replace({'mar':'Mar','apr':'Apr'},inplace=True)

In [434]:
df['Month'].unique()

array(['Jan', 'Feb', 'Mar', 'Apr', 'may', 'June', 'July', 'aug', 'sept',
       'oct', 'Nov', 'Dec'], dtype=object)

##### Convert all months to the Uppercase.

In [435]:
df['Month'] = df['Month'].str.upper()

In [436]:
df['Month'].unique()

array(['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUNE', 'JULY', 'AUG', 'SEPT',
       'OCT', 'NOV', 'DEC'], dtype=object)

In [437]:
df.sample(5)

      Year Month           State Number Meeting_Date
5643  2003   AUG  Santa Catarina  1.513     1/1/2003
5816  2017   APR       Sao Paulo     41     1/1/2017
5149  2007  JULY        rondonia    187     1/1/2007
5940  2001   NOV       Sao Paulo    168     1/1/2001
2774  2002   AUG     Mato Grosso  3.984     1/1/2002

##### Convert all columns names to UpperCase

In [438]:
df.columns = df.columns.str.upper()

In [439]:
df.sample(3)

      YEAR MONTH     STATE NUMBER MEETING_DATE
1227  2009   FEB     Ceara      8     1/1/2009
860   2000   AUG  Amazonas    180     1/1/2000
5069  2007   MAR  rondonia     20     1/1/2007

##### Convert the States data to capitalise()

In [440]:
df['STATE']=df['STATE'].str.capitalize()

In [441]:
df['STATE']

0            Acre
1            Acre
2            Acre
3            Acre
4            Acre
          ...
6449    Tocantins
6450    Tocantins
6451    Tocantins
6452    Tocantins
6453    Tocantins
Name: STATE, Length: 6424, dtype: object

In [442]:
df.sample(3)

      YEAR MONTH        STATE NUMBER MEETING_DATE
2760  2008  JULY  Mato grosso    116     1/1/2008
5183  2001  SEPT     Rondonia  1.927     1/1/2001
5036  2014   JAN     Rondonia     12     1/1/2014

##### Check that whether the Number Column contains numbers only or object type of data also we have

In [443]:
df['NUMBER'].unique()

array(['0 Fires', '10 Fires', '12 Fires', ..., '2.032', '833', '623'],
      shape=(1729,), dtype=object)

##### Count the total NaN values present in the Number column and replace NaN values.

In [444]:
df['NUMBER'].isna().sum()

np.int64(132)

##### Get all the NaN Value records so we can easily replace those NaN values with 0 or other value.

In [445]:
df[df['NUMBER'].isna()]

      YEAR MONTH      STATE NUMBER MEETING_DATE
68    2006   APR       Acre    NaN     1/1/2006
110   2008  JUNE       Acre    NaN     1/1/2008
127   2005  JULY       Acre    NaN     1/1/2005
206   2004   NOV       Acre    NaN     1/1/2004
217   2015   NOV       Acre    NaN     1/1/2015
...    ...   ...        ...    ...          ...
6305  2008   MAY  Tocantins    NaN     1/1/2008
6354  2017  JULY  Tocantins    NaN     1/1/2017
6383  2006  SEPT  Tocantins    NaN     1/1/2006
6415  1998   NOV  Tocantins    NaN     1/1/1998
6428  2011   NOV  Tocantins    NaN     1/1/2011

[132 rows x 5 columns]

##### Replace the NaN values and check whether you will get the Null values 0 or not

In [446]:
df['NUMBER'].replace(np.nan,0,inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_1532\414541358.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['NUMBER'].replace(np.nan,0,inplace=True)

In [447]:
df['NUMBER'].isna().sum()

np.int64(0)

In [448]:
df.sample(5)

      YEAR MONTH    STATE NUMBER MEETING_DATE
6060  2002   MAY  Sergipe      0     1/1/2002
4215  2009   AUG     Piau    790     1/1/2009
3768  2000   OCT  Paraiba    658     1/1/2000
6085  2007  JUNE  Sergipe      0     1/1/2007
349   2007  JUNE  Alagoas      0     1/1/2007

##### Still Number columns have some string data type so we need to convert string data type to Integer by replacing Fires to Null string.

In [449]:
df['NUMBER'].unique()

array(['0 Fires', '10 Fires', '12 Fires', ..., '2.032', '833', '623'],
      shape=(1729,), dtype=object)

##### Extract the numeric part (digits and optional decimal points) Remove 'Fires' and strip extra spaces

In [450]:
df['NUMBER'] = df['NUMBER'].str.replace('Fires', '', case=False).str.strip()

##### For Column Number change the Data type object to integer.

In [451]:
df['NUMBER'].unique()

array(['0', '10', '12', ..., '2.032', '833', '623'],
      shape=(1417,), dtype=object)

##### Rename 'NUMBER' to 'FIRES' and apply changes to the original df

In [452]:
df.rename(columns={'NUMBER': 'FIRES'}, inplace=True)

In [453]:
df.sample(3)

      YEAR MONTH        STATE FIRES MEETING_DATE
5289  2008   FEB      Roraima   138     1/1/2008
2622  2009   DEC  Mato grosso   171     1/1/2009
5436  2015  SEPT      Roraima    77     1/1/2015

##### Conver the Fires column data type to Integer. Round to 0 decimal places, then convert

In [454]:
df['FIRES'].isna().sum()

np.int64(132)

In [455]:
df['FIRES'].dtype

dtype('O')

In [456]:
df['FIRES'].replace(np.nan,0,inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_1532\4268486839.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FIRES'].replace(np.nan,0,inplace=True)

In [457]:
# 1. Convert strings (like '1.976') to floats first
df['FIRES'] = pd.to_numeric(df['FIRES'], errors='coerce')

# Converts 1.976 to 2
df['FIRES'] = df['FIRES'].round(0).astype('Int64')

In [458]:
df['FIRES'].dtype

Int64Dtype()

##### Check still any data type wants to change and null values to be handle or not

In [459]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   YEAR          6424 non-null   int64
 1   MONTH         6424 non-null   object
 2   STATE         6424 non-null   object
 3   FIRES         6424 non-null   Int64
 4   MEETING_DATE  6424 non-null   object
dtypes: Int64(1), int64(1), object(3)
memory usage: 307.4+ KB

##### For Meeting date we have already year and again in date column we have dd/mm/yyyy but Some Year and this meeting year is not same hence we will keep Year column as it is.

In [460]:
df['MEETING_DATE']

0       1/1/1998
1       1/1/1999
2       1/1/2000
3       1/1/2001
4       1/1/2002
          ...
6449    1/1/2012
6450    1/1/2013
6451    1/1/2014
6452    1/1/2015
6453    1/1/2016
Name: MEETING_DATE, Length: 6424, dtype: object

##### Replaces the original column Meeting date data type with the datetime data type

In [461]:
df['MEETING_DATE'] = pd.to_datetime(df['MEETING_DATE'])

##### Check once before saving the dataset whether all data will be cleared or not

In [462]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6424 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   YEAR          6424 non-null   int64
 1   MONTH         6424 non-null   object
 2   STATE         6424 non-null   object
 3   FIRES         6424 non-null   Int64
 4   MEETING_DATE  6424 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), int64(1), object(2)
memory usage: 307.4+ KB

In [463]:
df.sample(7)

      YEAR MONTH        STATE  FIRES MEETING_DATE
391   2009   AUG      Alagoas      0   2009-01-01
2655  2003   FEB  Mato grosso    108   2003-01-01
5830  2011   MAY    Sao paulo    136   2011-01-01
4782  1999   JAN          Rio     63   1999-01-01
171   2009  SEPT         Acre      1   2009-01-01
5021  1999   JAN     Rondonia      1   1999-01-01
3749  2001  SEPT      Paraiba    258   2001-01-01

##### Save the dataset to perform Data Operati0n and Visualization.

In [465]:
df.to_csv("CLEANED_AMAZON_FIRES_DATASET.csv", index=False)